Repository Leets-Official/Z-BE, pull requests merged in 2024-11, with the labels that each got.

#28 가입된 멤버 확인하는 로직 변경
  src/main/java/com/leets/team2/xclone/domain/auth/service/AuthService.java
  src/main/java/com/leets/team2/xclone/domain/member/entities/Member.java
  src/main/java/com/leets/team2/xclone/domain/member/repository/MemberRepository.java
  src/main/java/com/leets/team2/xclone/domain/member/service/MemberService.java
Labels: bug

#30 로그인시 kakao id로 멤버를 찾고 가져오도록 수정
  src/main/java/com/leets/team2/xclone/domain/auth/service/AuthService.java
  src/main/java/com/leets/team2/xclone/domain/member/entities/Member.java
  src/main/java/com/leets/team2/xclone/domain/member/repository/MemberRepository.java
  src/main/java/com/leets/team2/xclone/domain/member/service/MemberService.java
Labels: bug

#31 Feat#25 팔로우 도메인 기능 구현
  src/main/java/com/leets/team2/xclone/domain/follow/controller/FollowController.java
  src/main/java/com/leets/team2/xclone/domain/follow/dto/FollowDTO.java
  src/main/java/com/leets/team2/xclone/domain/follow/entity/Follow.java
  src/main/java/com/leets/team2/xclone/domain/follow/repository/FollowRepository.java
  src/main/java/com/leets/team2/xclone/domain/follow/service/FollowService.java
  src/main/java/com/leets/team2/xclone/domain/member/entities/Member.java
  src/main/java/com/leets/team2/xclone/domain/member/repository/MemberRepository.java
  src/main/java/com/leets/team2/xclone/exception/ErrorInfo.java
  src/main/java/com/leets/team2/xclone/exception/FollowAlreadyExistsException.java
  src/main/java/com/leets/team2/xclone/exception/InvalidFollowException.java
  src/main/java/com/leets/team2/xclone/exception/NoSuchFollowException.java
Labels: enhancement

#35 Refactor#34 팔로우 도메인 스웨거 설명 추가
  src/main/java/com/leets/team2/xclone/domain/follow/controller/FollowController.java
Labels: documentation

#26 Feat#21 게시물 생성, 삭제, 수정 API 구현
  src/main/java/com/leets/team2/xclone/domain/member/service/MemberService.java
  src/main/java/com/leets/team2/xclone/domain/post/controller/PostController.java
  src/main/java/com/leets/team2/xclone/domain/post/dto/PostDTO.java
  src/main/java/com/leets/team2/xclone/domain/post/dto/PostEditRequestDTO.java
  src/main/java/com/leets/team2/xclone/domain/post/dto/PostEditResponseDTO.java
  src/main/java/com/leets/team2/xclone/domain/post/dto/PostRequestDTO.java
  src/main/java/com/leets/team2/xclone/domain/post/dto/PostResponseDTO.java
  src/main/java/com/leets/team2/xclone/domain/post/entity/Post.java
  src/main/java/com/leets/team2/xclone/domain/post/repository/PostRepository.java
  src/main/java/com/leets/team2/xclone/domain/post/service/PostService.java
  src/main/java/com/leets/team2/xclone/exception/ErrorInfo.java
  src/main/java/com/leets/team2/xclone/exception/InvalidFileException.java
  src/main/java/com/leets/team2/xclone/exception/PostNotFoundException.java
  src/main/java/com/leets/team2/xclone/exception/UnauthorizedException.java
  src/main/java/com/leets/team2/xclone/exception/handler/GlobalExceptionHandler.java
Labels: enhancement

#41 인가 로직 구현
  src/main/java/com/leets/team2/xclone/common/auth/MemberContext.java
  src/main/java/com/leets/team2/xclone/common/auth/MemberExtractor.java
  src/main/java/com/leets/team2/xclone/common/auth/annotations/UseGuards.java
  src/main/java/com/leets/team2/xclone/common/auth/aop/UseGuardsAspect.java
  src/main/java/com/leets/team2/xclone/common/auth/guards/Guard.java
  src/main/java/com/leets/team2/xclone/common/auth/guards/MemberGuard.java
  src/main/java/com/leets/team2/xclone/exception/ErrorInfo.java
  src/main/java/com/leets/team2/xclone/exception/ExpiredTokenException.java
  src/main/java/com/leets/team2/xclone/exception/NotFoundAccessTokenException.java
  src/main/java/com/leets/team2/xclone/exception/NotFoundRefreshTokenException.java
Labels: enhancement

#40 Feat#39 S3를 이용한 이미지 업로드 기능 구현
  build.gradle
  src/main/java/com/leets/team2/xclone/config/AwsS3Config.java
  src/main/java/com/leets/team2/xclone/domain/post/controller/PostController.java
  src/main/java/com/leets/team2/xclone/domain/post/dto/PostEditRequestDTO.java
  src/main/java/com/leets/team2/xclone/domain/post/dto/PostEditResponseDTO.java
  src/main/java/com/leets/team2/xclone/domain/post/dto/PostRequestDTO.java
  src/main/java/com/leets/team2/xclone/domain/post/dto/PostResponseDTO.java
  src/main/java/com/leets/team2/xclone/domain/post/dto/RepostResponseDTO.java
  src/main/java/com/leets/team2/xclone/domain/post/entity/Post.java
  src/main/java/com/leets/team2/xclone/domain/post/service/PostService.java
  src/main/java/com/leets/team2/xclone/exception/ErrorInfo.java
  src/main/java/com/leets/team2/xclone/exception/InvalidFileException.java
  src/main/java/com/leets/team2/xclone/exception/UnsupportedFileFormatException.java
  src/main/java/com/leets/team2/xclone/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/leets/team2/xclone/image/converter/ImageListConverter.java
  src/main/java/com/leets/team2/xclone/image/service/ImageSaveService.java
Labels: enhancement

#46 Refactor#45 팔로우 로직 수정
  src/main/java/com/leets/team2/xclone/domain/follow/controller/FollowController.java
  src/main/java/com/leets/team2/xclone/domain/follow/service/FollowService.java
Labels: enhancement

#52 Feat#49 멤버 조회 및 프로필 사진 수정 api 추가
  src/main/java/com/leets/team2/xclone/domain/member/controller/MemberController.java
  src/main/java/com/leets/team2/xclone/domain/member/controller/MemberControllerImpl.java
  src/main/java/com/leets/team2/xclone/domain/member/dto/MemberDTO.java
  src/main/java/com/leets/team2/xclone/domain/member/entities/Member.java
  src/main/java/com/leets/team2/xclone/domain/member/service/MemberService.java
  src/main/java/com/leets/team2/xclone/image/converter/ImageListConverter.java
Labels: enhancement

#54 Refactor #53 PostEdit DTO 수정
  src/main/java/com/leets/team2/xclone/domain/post/dto/PostEditRequestDTO.java
Labels: enhancement

#56 fix: 게시글 생성/수정 시 사진 미첨부 시 발생하던 오류 수정
  src/main/java/com/leets/team2/xclone/domain/post/service/PostService.java
Labels: bug

#60 내 태그 가져오기 API 구현
  src/main/java/com/leets/team2/xclone/domain/member/controller/MemberController.java
  src/main/java/com/leets/team2/xclone/domain/member/controller/MemberControllerImpl.java
  src/main/java/com/leets/team2/xclone/domain/member/dto/responses/MemberTagGetResponse.java
Labels: enhancement
